# Generated by Django 5.1.3 on 2025-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_address_zip_code_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.CharField(default=False),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'address_type', 'default'), name='unique_user_address_type_default'),
        ),
    ]
