# Generated by Django 5.1.3 on 2024-11-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kitchen", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("photo", models.URLField()),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("photo", models.TextField(blank=True, null=True)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku", models.CharField(max_length=100)),
                ("cooking_time", models.TimeField(blank=True, null=True)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("DRINK", "Drink"),
                            ("DESSERT", "Dessert"),
                            ("COMBO", "Combo Meal"),
                            ("KIDS_MENU", "Kids Menu"),
                            ("SPECIALTY", "Specialty Item"),
                            ("SEASONAL", "Seasonal Item"),
                        ],
                        default="FOOD",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="product.category",
                    ),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="kitchen.kitchen",
                    ),
                ),
            ],
        ),
    ]
