# Generated by Django 5.1.3 on 2025-02-04 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_ingredient_order_due_payment_date_payment_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐☆☆☆☆ (Poor)'), (2, '⭐⭐☆☆☆ (Fair)'), (3, '⭐⭐⭐☆☆ (Good)'), (4, '⭐⭐⭐⭐☆ (Very Good)'), (5, '⭐⭐⭐⭐⭐ (Excellent)')])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.order')),
            ],
        ),
    ]
