# Generated by Django 5.1.3 on 2024-11-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_subcategory_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOP_RATED", "Top Rated"),
                    ("RECOMMENDED", "Recommended"),
                    ("NEWLY_LAUNCHED", "Newly Launched"),
                    ("DAILY_SPECIAL", "Daily Special"),
                    ("HOT", "Hot"),
                    ("TRENDING", "Trending"),
                    ("BEST_SELLER", "Best Seller"),
                    ("POPULAR", "Popular"),
                    ("FEATURED", "Featured"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
