import type { Metadata } from "next";
import { Oswald, Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";

const playfairDisplay = Playfair_Display({ // for heading
  variable: "--font-playfair-display",
  subsets: ["latin", 'cyrillic', 'latin-ext', "vietnamese"],
});

const oswald = Oswald({ // for action btn
  variable: "--font-oswald",
  subsets: ["latin", "cyrillic", "cyrillic-ext", "latin-ext", "vietnamese"],
  weight: ["300", "400", "700"],
});


const lato = Lato({ // for body or text 
  variable: "--font-lato",
  subsets: ["latin", 'latin-ext'],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${oswald.variable} ${lato.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
