# Generated by Django 5.1.3 on 2025-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
