# Generated by Django 5.1.3 on 2025-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_supplierpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
