# Generated by Django 5.1.3 on 2025-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_alert_quantity_item_alert_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alert_stock',
            field=models.IntegerField(default=0),
        ),
    ]
