# Generated by Django 5.1.3 on 2025-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_waste_total_loss_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
