# Generated by Django 5.1.3 on 2025-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplierpayment_status_supplierpayment_trx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
