# Generated by Django 5.1.3 on 2025-02-11 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplierinvoice_invoice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parchageinvoiceitem',
            name='supplier_order',
        ),
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parchageinvoiceitem',
            name='supplier_parchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parchage_items', to='inventory.supplierinvoice'),
        ),
        migrations.AlterField(
            model_name='parchageinvoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parchage_items', to='inventory.item'),
        ),
    ]
