# Generated by Django 5.1.3 on 2025-01-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productdescription_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='product.product'),
            preserve_default=False,
        ),
    ]
