# Generated by Django 5.1.3 on 2025-01-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productdescription_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='short_description',
        ),
    ]
