# Generated by Django 5.1.3 on 2025-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_attributeoption_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeoption',
            old_name='price',
            new_name='extra_price',
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
