# Generated by Django 5.1.3 on 2025-02-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributeoption')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderproduct')),
            ],
        ),
    ]
