# Generated by Django 5.1.3 on 2025-02-16 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_orderproductattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductattribute',
            name='extra_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='account_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderproductattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_attribute', to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='orderproductattribute',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_attribute', to='product.attributeoption'),
        ),
        migrations.AlterField(
            model_name='orderproductattribute',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_attribute', to='product.orderproduct'),
        ),
    ]
