# Generated by Django 5.1.3 on 2025-02-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productaccess_delete_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='product.orderproduct'),
        ),
    ]
