# Generated by Django 5.1.3 on 2025-01-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='admin',
        ),
    ]
